feat: 资源关系展示接口
idcos/CloudIaC pull request #107
Opened 2021-11-15 13:03 UTC by xiaohei417

2021-11-18 10:40 UTC, jxinging requested changes

2021-11-18 10:40 UTC, jxinging commented on portal/apps/task.go
> +		addrs := strings.Split(resource.Address, ".")
Address 中的 “module” 没有处理？

2021-11-18 10:40 UTC, jxinging commented on portal/apps/task.go
> +			nodeAttr[addr] = resource
这里 addr 会不会重复？
比如两个地址:
```
module.tf-instances.alicloud_instance.this[0]                                                              |
module.tf-instances.alicloud_instance.this[1]
```
这里面 tf-instances 和 alicloud_instance 都是会重复的

2021-11-25 01:49 UTC, xiaohei417 commented
#78

2021-11-25 02:56 UTC, jxinging approved these changes

2021-11-25 02:56 UTC, merged