# 77 添加偏移检测功能
idcos/CloudIaC pull request #124
Opened 2021-11-21 12:41 UTC by xuxiaoahang2018

2021-11-21 15:32 UTC, jxinging requested changes

2021-11-21 15:32 UTC, jxinging commented on portal/models/task.go
> +	return path.Join(t.ProjectId.String(), t.EnvId.String(), t.Id.String(), "step2", runner.TaskLogName)
如何确定是 step2？用户可以自定义 pipeline

而且这个路径也并未写入文件，参考：PlanJsonPath()，先了解这个文件路径是如何使用的

2021-11-21 15:32 UTC, jxinging commented on portal/apps/env.go
> +			task, err := services.CreateTask(session, tpl, env, pt)
这段代码是到指定时间后执行，直接使用传入的 pt，如何保证使用的是最新的 task 数据？

2021-11-21 15:32 UTC, jxinging commented on portal/apps/env.go
> +	if err := services.QueryActiveEnv(session).Find(&env); err != nil {
QueryActiveEnv() 会返回所有状态非 "inactive" 或者当前正在部署中的任务，实际这里我们是不是只查询当前为 active 状态的任务就可以了，如果环境为 failed 状态应该需要用户手动恢复。

引申：
1. 如果环境为 failed 状态，到了 cron 时间是否需要发起检测任务？
2. 如果开启了自动纠偏，当执行 apply 失败时是否应该将环境设置为 failed 状态？

2021-11-21 15:32 UTC, jxinging commented on portal/apps/env.go
> +			task, err := services.CreateTask(session, tpl, env, pt)
我们始终使用环境最后一次任务的数据(如变量、commit)执行偏移检测？
这样的话也应该是每次执行检测任务前通过 env.LastTaskId 来获取最新任务，因为用户不仅可以通过 EnvDeploy() 接口来执行环境部署，通过 trigger/send 也一样可以，后续还可能有新的接口加进来

2021-11-21 15:32 UTC, jxinging commented on portal/models/drift_task.go
> +	return "iac_cron_drift_task"
这个表实际保存的是资源的漂移信息，命名为 iac_resource_drift 更合适，包括结构体名

2021-11-21 15:32 UTC, jxinging commented on portal/apps/env.go
> +var CronEntryChan = make(chan models.Id)
CronEntryChan 这个名字不太符合实际用途

2021-11-21 15:32 UTC, jxinging commented on portal/apps/env.go
> +			CronInstance.Remove(EnvDriftTaskMap[envId])
portal 多实例部署时每个实例都有自己的 CronInstance，而每次环境部署都是随机路由到任意一个 portal 处理的，如果第一次部署由 portal A 处理，第二次部署由 portal B 处理，B 这里执行删除时将无法报到 cron 的 entryId

2021-11-22 13:59 UTC, jxinging requested changes

2021-11-22 13:59 UTC, jxinging commented on portal/apps/env.go
> +			err := DeleteCronEntryId(env.Id.String())
环境不活跃就要删除 cron 吗？如环境部署失败，重新部署后又成功了，此时 cron 任务还会不会启动？

2021-11-22 13:59 UTC, jxinging commented on portal/task_manager/manager.go
> +						if bs, err := readIfExist(task.TFPlanOutputLogPath(fmt.Sprintf("step%d", step.Index))); err != nil {
task.TFPlanOutputLogPath() 这个路径还是没有写入内容？
可以看下 task.PlanJsonPath() 这个路径会在任务结束后将相应的文件内容写入的，然后读取才会有内容

2021-11-22 13:59 UTC, jxinging commented on portal/apps/env.go
> +	CronInstance.Remove(cron.EntryID(drift.CronEntryId))
还是会存在数据不一致问题， portal A 和 portal B 的 cronInstance 是两个对象

2021-11-23 03:27 UTC, xuxiaoahang2018 commented on portal/apps/env.go
> +			err := DeleteCronEntryId(env.Id.String())
需要删除cron , 一个不活跃的资源，自动纠偏没有意义，还有可能创建已经被删除资源。

重新部署又成功，会重新启动cron任务，在deploy 代码中会去重新创建。

2021-11-23 03:39 UTC, jxinging commented on portal/models/env.go
> +	AutoRepairDrift     bool   `json:"autoRepairDrift" gorm:"default:false"`  // 是否进行自动纠偏
缺少是否开启漂移检测的标识。

参考原型，开启漂移和 cron 表达式是两个字段，用户保留 cron，但关闭漂移检测
![image](https://user-images.githubusercontent.com/2339647/142968023-3568bdf8-b803-45f3-aa89-0db0321a93bc.png)

2021-11-24 02:27 UTC, jxinging requested changes

2021-11-24 02:27 UTC, jxinging commented on portal/services/task.go
> +	query := tx.Where("env_id = ? and is_drift_task = true and  status = 'pending' or status='running'", envId)
status = 'pending' or status='running'

上面这段需要括起来，否则 status='running' 只查询了状态，前面的 env_id 等条件不生效

2021-11-24 02:27 UTC, jxinging commented on portal/task_manager/manager.go
> +		isBeginCronCondition := nowTime.Equal(*env.NextStartCronTaskTime)
时间判断可以直接通过 SQL 来比较

2021-11-24 02:27 UTC, jxinging commented on portal/services/task.go
> +	query := tx.Where("env_id = ? and is_drift_task = true and  status = 'pending' or status='running'", envId)
这个查询只是为了判断是否有这种任务的话可以使用 tx.Exists() 判断查询是否有值

2021-11-24 02:27 UTC, jxinging commented on portal/task_manager/manager.go
> +				_, err = services.CreateTask(m.db, nil, nil, *task)
考虑重新定义一个 CloneTask()? 讨论一下

2021-11-24 14:01 UTC, jxinging approved these changes

2021-11-24 14:03 UTC, merged