FIX：修复代码扫描检测出来的问题
idcos/cloudiac pull request #327
Opened 2022-02-16 08:44 UTC by xuxiaoahang2018

2022-02-17 09:53 UTC, jxinging requested changes

2022-02-17 09:53 UTC, jxinging commented on portal/models/task_flow.go
> -	EnvParse TaskFlow `json:"envParse" yaml:"envParse"`
envParse 为什么改为 parse?

2022-02-17 09:53 UTC, jxinging commented on portal/services/variables.go
> -	scopes := make([]string, 0)
我测试了一下，这一行改为下面这样就不会报 issue
```
var scopes []string
```

2022-02-17 09:53 UTC, jxinging commented on portal/services/vcsrv/github.go
> -	}
这段之前的代码是有 bug 的？有跟小黑对过吗

2022-02-17 09:53 UTC, jxinging commented on portal/task_manager/manager.go
> -		startErr, runErr := m.processStartStep(ctx, task, step, *runTaskReq)
这段是我修改 issue 的代码，又被还原了，解决冲突的时候没仔细看吗

2022-02-18 08:17 UTC, xuxiaoahang2018 commented on portal/services/vcsrv/github.go
> -	}
核对过，这里确实有是有bug的，他原先定义的ph 返回值没有处理就直接返回了

2022-02-18 09:06 UTC, closed without merging