fix: sonar bug: 105,106,107,153,154,155,156,157,158,159,160,161,162,1…
idcos/cloudiac pull request #328
Opened 2022-02-16 08:46 UTC by xiaohei417

…63,164,175,176,177,178,179,180,181,182,183,184,209,210,212,213

2022-02-17 15:09 UTC, jxinging submitted a review, later dismissed

2022-02-18 09:46 UTC, xiaohei417 commented on portal/apps/task.go
> +		c.Logger().WithField("task", "output").Errorf("%s", err)
done

2022-02-18 09:46 UTC, xiaohei417 commented on portal/libs/db/mysql_gorm.go
> +	selects, ok := s.db.Get("app:lazySelects") //nolint
done

2022-02-18 09:46 UTC, xiaohei417 commented on portal/apps/template.go
> +		c.Logger().WithField("action", "set webhook").Errorf("%v", err)
done

2022-02-18 10:19 UTC, jxinging requested changes
又有冲突了 😭

2022-02-18 13:45 UTC, merged