Fix: 修复屏蔽策略不生效问题
idcos/cloudiac pull request #355
Opened 2022-02-24 13:01 UTC by chenzhanjia-idcos

2022-02-24 13:48 UTC, jxinging requested changes

2022-02-24 13:48 UTC, jxinging commented on portal/services/policy.go
> +	policies, _, err := GetValidPolicies(query, scanTask.TplId, scanTask.EnvId)
GetScanTaskById() 返回 RecordNotFound 时 scanTask.TplId 访问空指定吗

2022-02-24 14:24 UTC, chenzhanjia-idcos commented on portal/services/policy.go
> +	policies, _, err := GetValidPolicies(query, scanTask.TplId, scanTask.EnvId)
已修复

2022-02-25 03:05 UTC, jxinging approved these changes

2022-02-25 03:05 UTC, merged