基于 tag 的 runner 匹配
idcos/cloudiac pull request #385
Opened 2022-03-11 03:24 UTC by linuxr

按照tags匹配runner，并且兼容之前按照id匹配runner的方式。
修改涉及的API主要内容包括：
1.  变更（PUT /api/v1/consul/tags/update）增加权限控制，只有平台管理员可以编辑runner的tag
2.  新增（GET /api/v1/runners/tags），返回所有的tags
3.  变更（POST /api/v1/envs），runner相关参数增加runner_tags数组，为了兼容之前的环境runner_id参数保留。
4.  变更（GET /api/v1/envs/{envId}），返回值中增加runner_tags信息。
5.  变更（GET /api/v1/envs），返回值中增加runner_tags信息。
6.  变更（POST /api/v1/envs/:id/deploy）deploy时，根据选择的runner_tags，确定一个runner_id

2022-03-11 09:15 UTC, jxinging requested changes

2022-03-11 09:15 UTC, jxinging commented on portal/services/env.go
> +		return validRunners[0].ID, nil
返回的 index 也随机一下吧，保证各 runner 均匀分配任务

2022-03-11 09:28 UTC, jxinging requested changes

2022-03-11 09:28 UTC, jxinging commented on utils/utils.go
> +			list = append(list[:index], list[index+1:]...)
list 值在 range 期间被修复，会导致异常。

RemoveDuplicateElement() 函数已经实现了该功能，可以直接调用

2022-03-11 09:28 UTC, jxinging commented on portal/apps/env.go
> +	env.RunnerId = runnerId
如果接口传入了 runnerTags，env.RunnerId 应该置为空，getRunnerId() 获取的 runnerId 应该保存到 task 表，这样才能保证每次执行任务都是基于 tags 匹配随机选择可用 runner

2022-03-11 16:07 UTC, linuxr commented on portal/apps/env.go
> +	env.RunnerId = runnerId
增加 runnerId是否为空的判断。
getRunnerId() 的错误沿调用路径返回。

2022-03-11 16:21 UTC, linuxr commented on portal/apps/env.go
> +	env.RunnerId = runnerId
setEnvByForm方法只设置env的runnerTags和runnerId，
task表创建之前根据env表的runnerTags和runnerId确定具体的 runnerId

2022-03-11 16:24 UTC, linuxr commented on portal/models/env.go
> +	RunnerTagsArr []string `json:"runnerTagsArr"`        // runner tags array
这个是在返回env信息的API中，增加一个字段，返回当前env的 runnertags列表，添加了 gorm:"-" 不在数据库表中创建字段

2022-03-11 16:29 UTC, linuxr commented on portal/services/env.go
> +		return validRunners[0].ID, nil
随机返回符合条件的runnerId

2022-03-11 16:36 UTC, linuxr commented on utils/utils.go
> +			list = append(list[:index], list[index+1:]...)
替换为 RemoveDuplicateElement函数

2022-03-13 07:25 UTC, jxinging approved these changes

2022-03-13 07:25 UTC, merged