Fix: 调整操作日志记录
idcos/cloudiac pull request #401
Opened 2022-03-18 07:00 UTC by chenzhanjia-idcos

2022-03-18 11:49 UTC, jxinging requested changes

2022-03-18 11:49 UTC, jxinging commented on portal/web/middleware/operation.go
> +		OperationInfo: fmt.Sprintf(getMsg(MsgOperationLogUpdate), parseRes(url), parseId(url)),
通过 url parseRes() 和 parseId() 是不是不太准确？
res 可以获取 AccessControl() 解析后得到的 object

2022-03-18 15:59 UTC, jxinging commented on portal/web/middleware/operation.go
> +		OperationInfo: fmt.Sprintf(getMsg(MsgOperationLogUpdate), parseRes(url), parseId(url)),
AccessControl 除了解析 url，还会解析入参 args 来确定 object，这边可以使用吗

2022-03-19 03:30 UTC, chenzhanjia-idcos commented on portal/web/middleware/operation.go
> +		OperationInfo: fmt.Sprintf(getMsg(MsgOperationLogUpdate), parseRes(url), parseId(url)),
AccessControl 里面的资源/操作替代是为了实现特定地址通过特定权限配置而进行替代，一般是重命名操作比较多，比如 PSOT envs/:env_id/deploy 替代识别为一个 deploy 动作而不是 POST；对于资源类型的替代比较少，目前只有 /auth/me 和 /users/self 这两个 API 替代为一个特别的 self 类资源，对于记录操作日志影响不大，我觉得可以维持现在 operation log 的解析方式，只解析 url 获取资源类型就足够了。

2022-03-21 08:51 UTC, jxinging approved these changes

2022-03-21 08:51 UTC, merged