Add: Support Ldap function
idcos/cloudiac pull request #411
Opened 2022-03-23 06:34 UTC by xuxiaoahang2018

2022-03-23 09:37 UTC, jxinging requested changes

2022-03-23 09:37 UTC, jxinging commented on portal/apps/auth.go
> +			ldapUser, err := CreateUser(c, createUserform)
apps 层的函数间应该避免相互调用，需要共用的逻辑可以封装到 services 层。

这里直接调用 apps.CreateUser() 会给用户创建一个初始密码，并通过邮件发送，但 ldap 用户在我们平台不应该有密码的（密码字段应该保存为空值）

2022-03-23 09:37 UTC, jxinging commented on portal/apps/user.go
> +func SearchLdapUser(c *ctx.ServiceContext, form *forms.SearchUserForm) (interface{}, e.Error) {
该接口要求最多返回匹配的前 10 条（后端强制限制）

2022-03-23 09:37 UTC, jxinging commented on portal/apps/auth.go
> +func LdapAuthLogin(userEmail, password string) (username string, er e.Error) {
这个函数移到 services 层

2022-03-23 09:37 UTC, jxinging commented on portal/apps/auth.go
> +				return nil, e.New(e.InvalidPassword, http.StatusBadRequest)
ldapErr 需要打印到日志，否则出错不便于排查问题

2022-03-23 09:37 UTC, jxinging commented on portal/apps/auth.go
> +	)
这个搜索条件是否具有通用性，对 ldap 环境有无要求，如 objectClass=organizationalPerson,mail=xx 这样的条件在客户环境中能否正常执行？

2022-03-24 03:35 UTC, xuxiaoahang2018 commented on portal/apps/auth.go
> +			ldapUser, err := CreateUser(c, createUserform)
createUserOrgRel 密码逻辑在  createUserOrgRel 里面进行了处理

2022-03-24 06:43 UTC, jxinging commented on portal/apps/auth.go
> +			ldapUser, err := CreateUser(c, createUserform)
我的意思是 ldap 登录的用户不需要在 iac 设置密码，即使设置了用这个密码也登录不了

2022-03-25 15:20 UTC, jxinging requested changes

2022-03-25 15:20 UTC, jxinging commented on portal/apps/user.go
> +		limit = form.PageSize()
limit 限制最大值为 10，如果这里读了 form.PageSize() 不是可以让前端随意传了吗

2022-03-25 15:20 UTC, jxinging commented on portal/apps/user.go
> +	p := page.New(form.CurrentPage(), limit, query)
form.CurrentPage() 应该总是传 1，因为我们的目的是要让用户只能看到前 10 条数据，如果 currentPage 可以传入，那用户就可以通过传入不同的 currentPage 值遍历数据了

2022-03-27 18:11 UTC, xuxiaoahang2018 commented on portal/apps/auth.go
> +	)
节选自  https://datatracker.ietf.org/doc/html/rfc2251
Some attributes, termed operational attributes, are used by servers
   for administering the directory system itself.  They are not returned
   in search results unless explicitly requested by name.  Attributes
   which are not operational, such as "mail", will have their schema and
   syntax constraints enforced by servers, but servers will generally
   not make use of their values.
   协议中搜索mail  相关解释只有这段说明

2022-03-28 11:07 UTC, jxinging approved these changes

2022-03-28 11:07 UTC, merged