Update: Resource search
idcos/cloudiac pull request #422
Opened 2022-03-25 11:08 UTC by xuxiaoahang2018

2022-03-25 15:06 UTC, jxinging requested changes

2022-03-25 15:06 UTC, jxinging commented on portal/web/api/v1/route.go
> +	g.GET("/orgs/envs_info", ac("orgs", "read"), w(handlers.Organization{}.SearchOrgEnvAndProvider))
/orgs/envs_info 改为 /orgs/resources/filters

2022-03-25 15:06 UTC, jxinging commented on portal/web/api/v1/route.go
> +	g.GET("/orgs/envs_info", ac("orgs", "read"), w(handlers.Organization{}.SearchOrgEnvAndProvider))
函数名也一样

2022-03-25 15:06 UTC, jxinging commented on portal/models/forms/organization.go
> +	EnvIds    []string `json:"env_ids" binding:""`    // 环境id列表
env_ids 统一用小驼峰风格

2022-03-27 17:47 UTC, xuxiaoahang2018 commented on portal/apps/organization.go
> +		r.Envs = append(r.Envs, resps.EnvResp{EnvName: v.EnvName, EnvId: v.EnvId})
envs 里的数据包含env_id,  后续查询也是根据env_id 查询， env_id 是唯一的。

2022-03-28 04:17 UTC, jxinging approved these changes
envs 和 providers 去重方案待优化

2022-03-28 04:17 UTC, merged