修改资源账号表相关表结构
idcos/cloudiac pull request #451
Opened 2022-03-30 04:50 UTC by linuxr

1. 资源账号表增加 CostEstimated，CostCounted， Provider 字段
2. 增加资源账号和项目的关联

2022-03-30 05:21 UTC, jxinging requested changes

2022-03-30 05:21 UTC, jxinging commented on portal/models/resource_account.go
> +	Provider      string `json:"provider" gorm:"type:enum('alicloud', 'aws', 'azure', 'google', 'tencentcloud', 'huaweicloud');comment:资源供应平台名称"` // 资源供应平台名称
Provider 允许用户自己输入，不需要限制

2022-03-30 05:21 UTC, jxinging commented on portal/models/project.go
> +	ResourceAccountId Id `json:"resourceAccountId" gorm:"size:32;comment:资源账号ID"` //资源账号ID
一个项目会多个资源账号，需要另一张关联表记录两者的关联

2022-03-30 07:08 UTC, linuxr commented on portal/models/project.go
> +	ResourceAccountId Id `json:"resourceAccountId" gorm:"size:32;comment:资源账号ID"` //资源账号ID
增加了新的关联表：iac_resource_account_project_rel

2022-03-30 07:08 UTC, linuxr commented on portal/models/resource_account.go
> +	Provider      string `json:"provider" gorm:"type:enum('alicloud', 'aws', 'azure', 'google', 'tencentcloud', 'huaweicloud');comment:资源供应平台名称"` // 资源供应平台名称
已去除限制

2022-03-31 03:48 UTC, xiaohei417 approved these changes

2022-03-31 08:12 UTC, jxinging approved these changes

2022-03-31 08:17 UTC, merged