优化表单校验报错提示
idcos/cloudiac pull request #494
Opened 2022-04-11 09:02 UTC by cong2960

2022-04-12 03:18 UTC, xiaohei417 commented
参考下 做下优化

func register() ut.Translator {
	var (
		uni      *ut.UniversalTranslator
		validate *validator.Validate
	)
	en := en.New()
	uni = ut.New(en, en)
	trans, _ := uni.GetTranslator("en")

	validate = binding.Validator.Engine().(*validator.Validate)
	err := en_translations.RegisterDefaultTranslations(validate, trans)
	if err != nil {
		panic(err)
	}

	registerTranslations(validate, trans)

	return trans
}

func re(v *validator.Validate, trans ut.Translator, tag string, customRegisFunc validator.RegisterTranslationsFunc, customTransFunc validator.TranslationFunc) {
	if err := v.RegisterTranslation(tag, trans, customRegisFunc, customTransFunc); err != nil {
		panic(err)
	}
}

func registerTranslations(v *validator.Validate, trans ut.Translator){
	f := func(ut ut.Translator, fe validator.FieldError) string {
		t, _ := ut.T(fe.Tag(), fe.Field(), fe.Param())
		return t
	}

	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	re(v, trans, "startswith", registrationFunc("startswith", "{0} must startswith {1}", false), f)
	return
}

func registrationFunc(tag string, translation string, override bool) validator.RegisterTranslationsFunc {
	return func(ut ut.Translator) (err error) {
		if err = ut.Add(tag, translation, override); err != nil {
			return
		}

		return
	}
}

func translateFunc(ut ut.Translator, fe validator.FieldError) string {
	t, err := ut.T(fe.Tag(), fe.Field())
	if err != nil {
		return fe.(error).Error()
	}

	return t
}

2022-04-14 01:58 UTC, xiaohei417 approved these changes

2022-04-14 01:59 UTC, xiaohei417 commented
提交代码之前做下 go fmt

2022-04-14 14:21 UTC, jxinging requested changes

2022-04-14 14:21 UTC, jxinging commented on portal/libs/ctx/request_ctx.go
> +	re(validate, tranEn, "startswith", registrationFunc("startswith", "{0} must startswith '{1}'", false), f)
tranZh 没有 startswitch 的翻译？

2022-04-15 06:10 UTC, jxinging approved these changes

2022-04-15 06:10 UTC, merged