fix consul重连时，相同ID的服务会卡住
idcos/cloudiac pull request #527
Opened 2022-04-22 15:30 UTC by linuxr

首次启动获取锁时，锁的参数LockTryOnce设置为true。

2022-04-24 04:11 UTC, jxinging requested changes

2022-04-24 04:11 UTC, jxinging commented on cmds/common/register.go
> +		lg.Errorf("%s service register failed: %v", serviceName, err)
服务注册失败应该尝试重新注册吧，或者主动释放锁重新走获取锁再注册服务的流程。否则会出现上锁了，但服务没有注册的情况

2022-04-24 05:37 UTC, linuxr commented on cmds/common/register.go
> +		lg.Errorf("%s service register failed: %v", serviceName, err)
已修改

2022-05-05 03:24 UTC, jxinging approved these changes

2022-05-05 03:24 UTC, merged