pipeline v0.5版本
idcos/cloudiac pull request #599
Opened 2022-06-02 02:41 UTC by linuxr

2022-06-07 04:07 UTC, jxinging requested changes

2022-06-07 04:07 UTC, jxinging commented on portal/services/task_pipeline.go
>  	err := yaml.NewDecoder(buffer).Decode(&p)
这里可以先解析获取 version，然后根据 version 匹配不同的解码方式

2022-06-07 04:07 UTC, jxinging commented on portal/models/task_pipeline_dot5.go
> +			continue
0.5 版本中所有步骤都是需要执行的，用户能改的只是 before, after 命令，即使 pipeline 中未写该步骤也应该要执行

2022-06-08 10:05 UTC, linuxr commented on portal/models/task_pipeline_dot5.go
> +      type: checkout
type已删除

2022-06-24 01:55 UTC, jxinging commented
before after 命令的日志分割需要改下

2022-06-27 07:11 UTC, jxinging approved these changes

2022-06-27 07:11 UTC, merged