环境自动部署和自动销毁功能
idcos/cloudiac pull request #690
Opened 2022-07-28 09:25 UTC by linuxr

文档：https://idcos.yuque.com/kyco54/rgsunw/blhqst

2022-07-28 14:53 UTC, jxinging requested changes

2022-07-28 14:53 UTC, jxinging commented on portal/apps/env.go
> +		return nil, e.New(e.BadParam, "cron 表达式为空")
错误提示要用英文

2022-07-28 14:53 UTC, jxinging commented on portal/models/env.go
> +	AutoDeployTTL    string `json:"autoDeployTtl" gorm:"default:'0'" example:"1h/1d"` // 生命周期
AutoDeployTTL 做什么使用？环境自动部署只有 cron 表达式的需求吧

2022-07-28 14:53 UTC, jxinging commented on portal/services/task_auto_deploy.go
> +func CreateAutoDeployTask(tx *db.Session, env *models.Env) (*models.Task, e.Error) {
这个函数可以跟 CreateAutoDestroyTask() 合并为一个吧，只是任务类型和名称有差异，其他都是一样的

2022-07-29 08:49 UTC, linuxr commented on portal/apps/env.go
> +		return nil, e.New(e.BadParam, "cron 表达式为空")
OK

2022-07-29 09:12 UTC, linuxr commented on portal/services/task_auto_deploy.go
> +func CreateAutoDeployTask(tx *db.Session, env *models.Env) (*models.Task, e.Error) {
参照deploy那个api，auto deploy的参数多一些。deploy和destroy从业务看是差别很大的功能，分开来写以后deploy或者destroy中需要扩展不同的操作时清晰一些。
省得写一些if/else。

2022-08-02 01:00 UTC, linuxr commented on portal/models/env.go
> +	AutoDeployTTL    string `json:"autoDeployTtl" gorm:"default:'0'" example:"1h/1d"` // 生命周期
去除了 deployttl的配置

2022-08-02 14:59 UTC, jxinging approved these changes

2022-08-02 14:59 UTC, merged