feat: vcstoken密文存储; 使用vcstoken时进行解密;vcs列表接口不返回token信息
idcos/CloudIaC pull request #99
Opened 2021-11-10 09:48 UTC by xiaohei417

2021-11-10 10:00 UTC, xiaohei417 commented
#82

2021-11-11 03:10 UTC, jxinging requested changes

2021-11-11 03:10 UTC, jxinging commented on portal/models/vcs.go
> +func (v *Vcs) Decrypt() (string, error) {
Decrypt() -> DecryptToken()

2021-11-11 07:08 UTC, jxinging approved these changes

2021-11-11 07:08 UTC, merged